function report = type1_validate_phase3_part_a()
%TYPE1_VALIDATE_PHASE3_PART_A Frozen R16 algebraic regressions.
%   No BER/SINR scan is run here.  These four tests establish the physical
%   and algebraic foundation required before Part-B optimization.

seed = 20260716;
stream = RandStream('mt19937ar', 'Seed', seed);

%% 1) M=N, S=I must be bitwise identical to the Phase-2 switch.
model4 = type1_phase3_config(4, 4);
identitySchedule = type1_phase3_make_schedule(eye(4), model4);
raw4 = randn(stream, 1024, 4) + 1j*randn(stream, 1024, 4);
[oldStitched, oldVirtual] = type1_digital_switch(raw4);
[newStitched, newVirtual, scalarMeta] = ...
    type1_phase3_single_chain(raw4, identitySchedule);
identityStitchedExact = isequal(oldStitched, newStitched);
identityVirtualExact = isequal(oldVirtual, newVirtual);
assert(identityStitchedExact && identityVirtualExact && ...
    scalarMeta.digitizedOutputColumns == 1, 'type1:Phase3IdentityRegression', ...
    'M=N,S=I is not bitwise identical to the frozen four-phase path.');

%% 2) Ideal scalar switch must equal v=r*S and Htilde=S.'*H.
model8 = type1_phase3_config(8, 4);
S8 = [eye(4); 1 1 0 0; 0 1 1 0; 0 0 1 1; 1 0 0 1];
schedule8 = type1_phase3_make_schedule(S8, model8);
nSymbols = 256;
physical = randn(stream, nSymbols, 8) + 1j*randn(stream, nSymbols, 8);
rawRepeated = repelem(physical, 4, 1);
[~, virtual8, scalarMeta8] = type1_phase3_single_chain(rawRepeated, schedule8);
directVirtual = physical * S8;
idealSwitchRelativeError = norm(virtual8-directVirtual, 'fro') / ...
    max(norm(directVirtual, 'fro'), eps);
H = randn(stream, 8, 4) + 1j*randn(stream, 8, 4);
x = randn(stream, nSymbols, 4) + 1j*randn(stream, nSymbols, 4);
Htilde = type1_phase3_effective_channel(H, S8);
channelRelativeError = norm((x*H.')*S8 - x*Htilde.', 'fro') / ...
    max(norm(x*Htilde.', 'fro'), eps);
cfg = type1_config();
[tdlRx, tdlMeta] = type1_phase3_make_tdl_a_channel(x, cfg, model8, ...
    RandStream('mt19937ar', 'Seed', seed+1));
geometryPassed = isequal(size(tdlRx), [nSymbols 8]) && ...
    isequal(size(tdlMeta.gains), [8 4 23]) && ...
    tdlMeta.minimumRxCorrelationEigenvalue >= -1e-10 && ...
    isequal(tdlMeta.positionsLambda, model8.positionsLambda);
assert(idealSwitchRelativeError <= 1e-14 && channelRelativeError <= 1e-14 && ...
    scalarMeta8.digitizedOutputColumns == 1 && geometryPassed, ...
    'type1:Phase3IdealSwitchRegression', ...
    'Ideal M>N scalar switch/effective-channel algebra is inconsistent.');

%% 3) A-to-S projection and duty accounting must be conserved.
dutyFromA = reshape(sum(schedule8.A, 3), 8, 4);
dutyProjectionExact = isequal(double(dutyFromA), S8);
dutyCountExact = isequal(schedule8.dutyCount, sum(S8, 2));
assignmentCountExact = schedule8.totalAssignments == sum(S8, 'all');
dutyRejectCaught = false;
limited = model8; limited.maxDutyCount = 1;
try
    type1_phase3_make_schedule(S8, limited);
catch exception
    dutyRejectCaught = strcmp(exception.identifier, 'type1:Phase3DutyCycle');
end
assert(dutyProjectionExact && dutyCountExact && assignmentCountExact && ...
    dutyRejectCaught, 'type1:Phase3DutyConservation', ...
    'Duty-cycle conservation or its hard limit is not enforced.');

%% 4) Same-phase analog fan-out must be rejected with a stable identifier.
illegalA = identitySchedule.A;
illegalA(1, 2, 1) = true;
illegalFanoutCaught = false;
try
    type1_phase3_validate_schedule(illegalA, model4);
catch exception
    illegalFanoutCaught = strcmp(exception.identifier, ...
        'type1:Phase3IllegalFanout');
end
assert(illegalFanoutCaught, 'type1:Phase3IllegalFanoutRegression', ...
    'An illegal same-phase fan-out schedule was accepted.');

report = struct;
report.phase = "Phase 3 Part A";
report.reviewTarget = "R16";
report.seed = seed;
report.mnIdentity = struct('passed', true, ...
    'stitchedBitwiseExact', identityStitchedExact, ...
    'virtualBitwiseExact', identityVirtualExact, ...
    'digitizedOutputColumns', scalarMeta.digitizedOutputColumns);
report.idealSwitch = struct('passed', true, ...
    'virtualRelativeError', idealSwitchRelativeError, ...
    'effectiveChannelRelativeError', channelRelativeError, ...
    'mPhysical', 8, 'nVirtual', 4, ...
    'digitizedOutputColumns', scalarMeta8.digitizedOutputColumns, ...
    'tdlGeometryPassed', geometryPassed, ...
    'tdlMinCorrelationEigenvalue', ...
        tdlMeta.minimumRxCorrelationEigenvalue, ...
    'positionsLambda', tdlMeta.positionsLambda);
report.dutyConservation = struct('passed', true, ...
    'projectionExact', dutyProjectionExact, ...
    'countsExact', dutyCountExact, ...
    'assignmentCountExact', assignmentCountExact, ...
    'limitRejectCaught', dutyRejectCaught, ...
    'dutyCount', schedule8.dutyCount, ...
    'transitionCount', schedule8.transitionCount);
report.illegalFanout = struct('passed', true, ...
    'stableIdentifier', "type1:Phase3IllegalFanout", ...
    'rejectCaught', illegalFanoutCaught);
report.allPassed = true;

fprintf(['Phase-3 Part-A R16 validation PASSED: identity exact=%d/%d, ' ...
    'ideal relerr=%.3g, Htilde relerr=%.3g, duty/reject=%d/%d, ' ...
    'illegal fanout reject=%d.\n'], identityStitchedExact, ...
    identityVirtualExact, idealSwitchRelativeError, channelRelativeError, ...
    dutyProjectionExact && dutyCountExact && assignmentCountExact, ...
    dutyRejectCaught, illegalFanoutCaught);
end
