function result = type1_run_phase3_r17_exhaustive()
%TYPE1_RUN_PHASE3_R17_EXHAUSTIVE Exact M=8 gate-1 TDL benchmark.

validation = type1_validate_phase3_exhaustive();
profile = lower(string(getenv('TYPE1_R17_PROFILE')));
if strlength(profile) == 0, profile = "paper"; end
assert(any(profile == ["smoke" "paper"]), 'type1:R17Profile', ...
    'TYPE1_R17_PROFILE must be smoke or paper.');
if profile == "paper", nSeeds = 20; else, nSeeds = 3; end

cfg = type1_config();
model = type1_phase3_config(8, 4); model.maxDutyCount = 1;
candidates = type1_phase3_enumerate_pair_partitions();
nCandidates = size(candidates, 3);
snrDb = 20;
seedValues = 20261701 + (0:nSeeds-1);
fullFrequencyHz = (-306:305) * cfg.scsKHz * 1e3;
rbToneIndices = 6:12:606;
baselineS = [eye(4); zeros(4)];
fixedS = false(8, 4);
for user = 1:4, fixedS(2*user-1:2*user, user) = true; end

preRegistration = struct('reviewTarget', "R17 gate 1", ...
    'profile', profile, 'nSeeds', nSeeds, 'seedValues', seedValues, ...
    'snrDb', snrDb, 'mPhysical', 8, 'nVirtual', 4, ...
    'portsPerVirtual', 2, 'maxDutyCount', 1, ...
    'candidateCount', nCandidates, ...
    'searchToneIndices', rbToneIndices, 'searchToneCount', numel(rbToneIndices), ...
    'evaluationToneCount', numel(fullFrequencyHz), ...
    'objective', "min-user mean post-MMSE SINR in dB", ...
    'noiseModel', "Rn=sigma2*S.'*S", ...
    'positiveFractionThreshold', 0.8, ...
    'medianGainThresholdDb', 0, 'signTestAlpha', 0.05, ...
    'impairmentsEnabled', false, 'acquisitionEnabled', false);

template = struct('seed', nan, 'noiseVariance', nan, ...
    'baselineSearch', struct, 'fixedSearch', struct, 'bestSearch', struct, ...
    'baselineFull', struct, 'fixedFull', struct, 'bestFull', struct, ...
    'bestIndex', nan, 'bestS', false(8,4), ...
    'candidateObjectiveDb', zeros(nCandidates,1), ...
    'gainDb', nan, 'rateGain', nan);
perSeed = repmat(template, nSeeds, 1);

for seedIndex = 1:nSeeds
    seed = seedValues(seedIndex);
    stream = RandStream('mt19937ar', 'Seed', seed);
    [~, channel] = type1_phase3_make_tdl_a_channel( ...
        complex(zeros(64, 4)), cfg, model, stream);
    Hfull = type1_phase3_tdl_frequency_response(channel, fullFrequencyHz);
    Hsearch = Hfull(:, :, rbToneIndices);
    physicalSignalPower = mean(sum(abs(Hfull).^2, 2), 'all');
    noiseVariance = physicalSignalPower / 10^(snrDb/10);

    objective = zeros(nCandidates, 1);
    for candidate = 1:nCandidates
        metric = type1_phase3_wideband_metrics( ...
            Hsearch, candidates(:, :, candidate), noiseVariance);
        objective(candidate) = metric.objectiveDb;
    end
    [~, bestIndex] = max(objective);
    bestS = candidates(:, :, bestIndex);
    baselineSearch = type1_phase3_wideband_metrics(Hsearch, baselineS, noiseVariance);
    fixedSearch = type1_phase3_wideband_metrics(Hsearch, fixedS, noiseVariance);
    bestSearch = type1_phase3_wideband_metrics(Hsearch, bestS, noiseVariance);
    baselineFull = type1_phase3_wideband_metrics(Hfull, baselineS, noiseVariance);
    fixedFull = type1_phase3_wideband_metrics(Hfull, fixedS, noiseVariance);
    bestFull = type1_phase3_wideband_metrics(Hfull, bestS, noiseVariance);
    perSeed(seedIndex) = struct('seed', seed, 'noiseVariance', noiseVariance, ...
        'baselineSearch', strip_sinr(baselineSearch), ...
        'fixedSearch', strip_sinr(fixedSearch), ...
        'bestSearch', strip_sinr(bestSearch), ...
        'baselineFull', strip_sinr(baselineFull), ...
        'fixedFull', strip_sinr(fixedFull), ...
        'bestFull', strip_sinr(bestFull), ...
        'bestIndex', bestIndex, 'bestS', bestS, ...
        'candidateObjectiveDb', objective, ...
        'gainDb', bestFull.objectiveDb-baselineFull.objectiveDb, ...
        'rateGain', bestFull.minUserRate-baselineFull.minUserRate);
    fprintf(['R17 %2d/%d seed=%d: minSINR base/fixed/best=' ...
        '%.3f/%.3f/%.3f dB, paired gain=%+.3f dB.\n'], ...
        seedIndex, nSeeds, seed, baselineFull.objectiveDb, ...
        fixedFull.objectiveDb, bestFull.objectiveDb, perSeed(seedIndex).gainDb);
end

gainDb = [perSeed.gainDb].';
positiveCount = sum(gainDb > 0);
positiveFraction = positiveCount / nSeeds;
medianGainDb = median(gainDb);
signTestP = exact_sign_test(positiveCount, nSeeds);
medianCiDb = paired_bootstrap_median_ci(gainDb, 20261799, 10000);
isPaper = profile == "paper";
gatePassed = isPaper && positiveFraction >= ...
    preRegistration.positiveFractionThreshold && ...
    medianGainDb > preRegistration.medianGainThresholdDb && ...
    signTestP < preRegistration.signTestAlpha;
summary = struct('positiveCount', positiveCount, 'nSeeds', nSeeds, ...
    'positiveFraction', positiveFraction, 'medianGainDb', medianGainDb, ...
    'gainRangeDb', [min(gainDb) max(gainDb)], ...
    'medianGainBootstrap95Db', medianCiDb, ...
    'oneSidedExactSignP', signTestP, 'gatePassed', gatePassed, ...
    'paperGateEvaluated', isPaper);

root = string(getenv('TYPE1_PHASE3_OUTPUT_ROOT'));
if strlength(root) == 0, root = fullfile(tempdir, 'type1_phase3'); end
if ~isfolder(root), mkdir(root); end
outputDirectory = fullfile(root, ['type1_phase3_r17_' char(profile) '_' ...
    char(datetime('now','Format','yyyyMMdd_HHmmss'))]);
mkdir(outputDirectory);
result = struct('preRegistration', preRegistration, 'validation', validation, ...
    'summary', summary, 'perSeed', perSeed, ...
    'outputDirectory', outputDirectory, 'createdAt', datetime('now'), ...
    'matlabVersion', version);
save(fullfile(outputDirectory, 'phase3_r17_exhaustive.mat'), 'result', '-v7.3');
plot_result(result, fullfile(outputDirectory, 'phase3_r17_exhaustive.png'));
fprintf(['R17 gate-1 %s: positive=%d/%d, median gain=%+.3f dB ' ...
    '(bootstrap95=[%+.3f,%+.3f]), sign p=%.6g, gatePassed=%d.\n'], ...
    profile, positiveCount, nSeeds, medianGainDb, medianCiDb(1), ...
    medianCiDb(2), signTestP, gatePassed);
fprintf('Phase-3 R17 audit saved: %s\n', outputDirectory);
end

function compact = strip_sinr(metric)
compact = rmfield(metric, 'sinrLinear');
end

function p = exact_sign_test(positive, total)
p = 0;
for k = positive:total, p = p + nchoosek(total, k) * 0.5^total; end
end

function interval = paired_bootstrap_median_ci(values, seed, repetitions)
stream = RandStream('mt19937ar', 'Seed', seed);
n = numel(values); draws = zeros(repetitions, 1);
for k = 1:repetitions
    draws(k) = median(values(randi(stream, n, n, 1)));
end
interval = prctile(draws, [2.5 97.5]);
end

function plot_result(result, outputFile)
seed = [result.perSeed.seed];
baseline = arrayfun(@(x)x.baselineFull.objectiveDb, result.perSeed);
fixed = arrayfun(@(x)x.fixedFull.objectiveDb, result.perSeed);
best = arrayfun(@(x)x.bestFull.objectiveDb, result.perSeed);
gain = [result.perSeed.gainDb];
figure('Visible','off','Position',[100 100 1300 480]);
subplot(1,2,1); plot(seed,baseline,'o-','LineWidth',1.2); hold on;
plot(seed,fixed,'s-','LineWidth',1.2); plot(seed,best,'^-','LineWidth',1.2);
grid on; xlabel('TDL seed'); ylabel('wideband min-user SINR (dB)');
legend('M=4 identity','M=8 fixed pairs','M=8 exhaustive','Location','best');
title('Paired gate-1 objectives');
subplot(1,2,2); stem(seed,gain,'filled','LineWidth',1.1); yline(0,'k--'); grid on;
xlabel('TDL seed'); ylabel('exhaustive - M=4 gain (dB)');
title(sprintf('positive=%d/%d, median=%+.2f dB, p=%.3g', ...
    result.summary.positiveCount,result.summary.nSeeds, ...
    result.summary.medianGainDb,result.summary.oneSidedExactSignP));
exportgraphics(gcf,outputFile,'Resolution',180); close(gcf);
end
