function audit = type1_audit_phase2_r15_metrics(campaignFile)
%TYPE1_AUDIT_PHASE2_R15_METRICS Preserve both R15 normalization semantics.
%   The project preregistered EVM residual power after interpreting the
%   expert's generic normalized-increment instruction.  The literal RMS-EVM
%   increment is derived without rerunning, changing seeds, or overwriting
%   the preregistered result.  This audit prevents post-hoc metric switching.

arguments
    campaignFile (1,1) string
end
loaded=load(campaignFile,'campaign');campaign=loaded.campaign;
rows=campaign.rows;
otaRms=rows.impairedEVMPercent./rows.idealEVMPercent-1;
offlineRms=sqrt(1+rows.offlineEvmPowerIncrement)-1;
assert(max(abs((1+otaRms).^2-1-rows.otaEvmPowerIncrement))<1e-12, ...
    'type1:R15MetricIdentity','OTA RMS/power increment identity failed.');
signAgreement=mean(sign(otaRms)==sign(offlineRms));
otaMedian=median(otaRms,'omitnan');offlineMedian=median(offlineRms,'omitnan');
medianRatio=otaMedian/offlineMedian;
literalPassed=signAgreement>=.9 && otaMedian>0 && offlineMedian>0 && ...
    medianRatio>=.5 && medianRatio<=2;
gains=unique(rows.rxGainDb);byGain=table('Size',[numel(gains) 10], ...
    'VariableTypes',repmat("double",1,10),'VariableNames', ...
    {'rxGainDb','count','snrMedianDb','snrMinDb','snrMaxDb', ...
    'otaPowerMedian','offlinePowerMedian','powerRatio', ...
    'otaRmsMedian','rmsRatio'});
for k=1:numel(gains)
    use=rows.rxGainDb==gains(k);
    byGain{k,:}=[gains(k),sum(use),median(rows.snrNullDb(use)), ...
        min(rows.snrNullDb(use)),max(rows.snrNullDb(use)), ...
        median(rows.otaEvmPowerIncrement(use)), ...
        median(rows.offlineEvmPowerIncrement(use)), ...
        median(rows.otaEvmPowerIncrement(use))/median(rows.offlineEvmPowerIncrement(use)), ...
        median(otaRms(use)),median(otaRms(use))/median(offlineRms(use))];
end
audit=struct('createdAt',datetime('now'),'sourceCampaignFile',campaignFile, ...
    'preregisteredPowerSummary',campaign.summary,'otaRmsIncrements',otaRms, ...
    'offlineRmsIncrements',offlineRms,'literalRmsSummary',struct( ...
        'signAgreement',signAgreement,'otaMedianIncrement',otaMedian, ...
        'offlineMedianIncrement',offlineMedian,'medianRatio',medianRatio, ...
        'acceptancePassed',literalPassed),'byGain',byGain, ...
    'adjudicationRequired',campaign.summary.acceptancePassed~=literalPassed);
[folder,~,~]=fileparts(campaignFile);
outFile=fullfile(folder,'type1_phase2_r15_metric_audit.mat');
save(outFile,'audit','-v7.3');
fprintf(['R15 prereg EVM^2 PASS=%d, ratio=%.6f; literal RMS-EVM PASS=%d, ' ...
    'ratio=%.6f; adjudicationRequired=%d\n'], ...
    campaign.summary.acceptancePassed,campaign.summary.medianRatio, ...
    literalPassed,medianRatio,audit.adjudicationRequired);
disp(byGain);fprintf('Saved %s\n',outFile);
end
