function report=type1_run_paper_e3_mobility_mapping()
%TYPE1_RUN_PAPER_E3_MOBILITY_MAPPING Map scan/update period to mobility.
%   Uses the frozen Clarke/Jakes 50%-coherence approximation
%   T_c=0.423/f_D and f_D=v/lambda.  This is an analytical applicability
%   boundary, not a measured tracking result.
carrierHz=3.2e9;lightSpeedMps=3e8;wavelengthM=lightSpeedMps/carrierHz;
updateSec=[.05 .1 .2 .5 1 2 5 10];coherenceFraction=.423;
maximumSpeedMps=coherenceFraction*wavelengthM./updateSec;
maximumSpeedKmh=3.6*maximumSpeedMps;
preRegistration=struct('reviewTarget',"Paper E3 scan-period mobility mapping", ...
    'carrierHz',carrierHz,'lightSpeedMps',lightSpeedMps, ...
    'wavelengthM',wavelengthM,'updateSec',updateSec, ...
    'coherenceModel',"Clarke/Jakes T_c=0.423/f_D; f_D=v/lambda", ...
    'interpretation',"maximum speed whose nominal 50%-coherence time is at least the update period", ...
    'boundary',"analytical mapping only; no closed-loop mobility tracker is claimed");
reconstructed=.423./(maximumSpeedMps/wavelengthM);
validation=struct('maximumRelativeIdentityError',max(abs(reconstructed-updateSec)./updateSec), ...
    'speedMonotonicDecreasing',all(diff(maximumSpeedMps)<0), ...
    'allPassed',max(abs(reconstructed-updateSec)./updateSec)<1e-14&&all(diff(maximumSpeedMps)<0));
assert(validation.allPassed,'type1:E3Validation','E3 unit/identity validation failed.');
mapping=table(updateSec(:),maximumSpeedMps(:),maximumSpeedKmh(:), ...
    'VariableNames',{'updatePeriodSec','maximumSpeedMps','maximumSpeedKmh'});
root=string(getenv('TYPE1_PAPER_OUTPUT_ROOT'));if strlength(root)==0,root=fullfile(tempdir,'type1_paper');end
if ~isfolder(root),mkdir(root);end
out=fullfile(root,['type1_paper_e3_' char(datetime('now','Format','yyyyMMdd_HHmmss'))]);mkdir(out);
report=struct('preRegistration',preRegistration,'validation',validation, ...
    'mapping',mapping,'summary',struct('speedAt100msMps',maximumSpeedMps(updateSec==.1), ...
    'speedAt100msKmh',maximumSpeedKmh(updateSec==.1), ...
    'speedAt1sMps',maximumSpeedMps(updateSec==1)), ...
    'outputDirectory',out,'createdAt',datetime('now'),'matlabVersion',version);
save(fullfile(out,'paper_e3_mobility_mapping.mat'),'report');
writetable(mapping,fullfile(out,'paper_e3_mobility_mapping.csv'));
figure('Visible','off','Position',[100 100 760 480]);loglog(updateSec,maximumSpeedKmh,'o-','LineWidth',1.8);
grid on;xlabel('port-scan / selection-update period (s)');ylabel('maximum nominal speed (km/h)');
title('T_c=0.423/f_D mobility applicability boundary');
exportgraphics(gcf,fullfile(out,'paper_e3_mobility_mapping.png'),'Resolution',180);close(gcf);
fprintf('E3: at 3.2 GHz, 100 ms maps to %.3f m/s (%.3f km/h).\n', ...
    report.summary.speedAt100msMps,report.summary.speedAt100msKmh);
fprintf('Paper E3 audit saved: %s\n',out);
end
