function type1_validate_ici_decision_feedback()
%TYPE1_VALIDATE_ICI_DECISION_FEEDBACK Ideal-link regression for R3/R4 receiver.
p=type1_load_package();s=type1_offline_sim_config();s.frames=1;s.assertIdealBaseline=false;
link=type1_offline_link(p,s,RandStream('mt19937ar','Seed',20260719));
rSoft=type1_analyze_ici_decision_feedback(link.virtualRx30,p,6,3,'soft');
rHard=type1_analyze_ici_decision_feedback(link.virtualRx30,p,6,3,'hard');
rDouble=type1_analyze_ici_decision_feedback(link.virtualRx30,p,6,3,'soft',false,false,'double');
rDdce=type1_analyze_ici_decision_feedback(link.virtualRx30,p,6,3,'soft',false,false,'single','ddce');
rPhysical=type1_analyze_ici_decision_feedback(link.virtualRx30,p,6,3,'soft',false,false,'double','fixed','physical');
rCombined=type1_analyze_ici_decision_feedback(link.virtualRx30,p,6,3,'soft',false,false,'double','ddce','physical');
[drive30,~]=type1_received_drive(link.stitched122,s.switch.settlingRiseNs,s.switch.rawSampleRateHz);
rReceived=type1_analyze_ici_decision_feedback(link.virtualRx30,p,6,3,'soft',false,false,'single','ddce','received',drive30);
assert(all(rSoft.infoBitErrors==0,'all') && all(rHard.infoBitErrors==0,'all') && ...
    all(rDouble.infoBitErrors==0,'all') && all(rDdce.infoBitErrors==0,'all') && ...
    all(rPhysical.infoBitErrors==0,'all') && all(rCombined.infoBitErrors==0,'all') && ...
    all(rReceived.infoBitErrors==0,'all'), ...
    'type1:ICIDF','ICI DF failed ideal-link zero-BER regression.');
assert(all(rSoft.trainingRows(:,[1 2 4:14],:)>0,'all'), ...
    'type1:ICIDF','Cross-fit training rows missing.');
assert(all(rSoft.trainingRowsByIteration(:,[1 2 4:14],:,:)>0,'all') && ...
    all(rHard.trainingRowsByIteration(:,[1 2 4:14],:,:)>0,'all'), ...
    'type1:ICIDF','Cross-fit training rows missing from an iteration.');
assert(rDouble.kernelBankCount==2 && size(rDouble.kernel,1)==2*(2*6+1), ...
    'type1:ICIDF','Double-bank kernel dimensions are inconsistent.');
assert(rPhysical.kernelRealDof==13 && size(rPhysical.kernel,1)==13, ...
    'type1:ICIDF','Physical constrained-kernel dimensions are inconsistent.');
assert(rReceived.kernelRealDof==13 && size(rReceived.kernel,1)==13, ...
    'type1:ICIDF','Received-drive constrained-kernel dimensions are inconsistent.');
fprintf('ICI decision-feedback single/double/DDCE/physical/received ideal regression PASSED (BER=0).\n');
end
