function report = type1_validate_rx_lo_phase_noise()
%TYPE1_VALIDATE_RX_LO_PHASE_NOISE Algebra/PSD/compatibility checks for R12.
cfg=type1_config(); model=struct('mode',"common",'phaseRmsDeg',2, ...
    'bandwidthHz',100e3,'seed',20261291,'recordTimeSeries',true);

% V1: sigma=0 and off are exact identities and consume no enclosing stream.
x=complex(reshape(1:4096,1024,4),reshape(4097:8192,1024,4));
zero=model; zero.phaseRmsDeg=0;
[yzero,~]=type1_apply_rx_lo_phase_noise(x,zero,cfg.txSampleRate);
off=model; off.mode="off";
[yoff,~]=type1_apply_rx_lo_phase_noise(x,off,cfg.txSampleRate);
assert(isequal(yzero,x) && isequal(yoff,x),'type1:RxLoIdentity', ...
    'RX-LO zero/off path is not bitwise identical.');

% V2: common topology applies exactly one phase to all simultaneous columns.
[ycommon,commonMeta]=type1_apply_rx_lo_phase_noise(ones(2^15,4),model,cfg.txSampleRate);
assert(max(abs(ycommon-ycommon(:,1)),[],'all')<1e-14 && ...
    size(commonMeta.phaseRad,2)==1,'type1:RxLoCommonPhase', ...
    'Common RX-LO did not apply one identical simultaneous phase.');

% V3: numerical SSB PSD at f=B/10 agrees with the bounded OU anchor.
nPsd=2^20; [~,psdMeta]=type1_apply_rx_lo_phase_noise(ones(nPsd,1),model,cfg.txSampleRate);
phase=psdMeta.phaseRad; window=hann(2^15,'periodic');
[sOneSided,f]=pwelch(phase,window,numel(window)/2,2^17,cfg.txSampleRate,'onesided');
targetHz=model.bandwidthHz/10; [~,bin]=min(abs(f-targetHz));
measuredL=.5*sOneSided(bin); sigma=deg2rad(model.phaseRmsDeg);
expectedL=sigma^2/(pi*model.bandwidthHz)/(1+(f(bin)/model.bandwidthHz)^2);
psdErrorDb=10*log10(measuredL/expectedL);
assert(abs(psdErrorDb)<=1,'type1:RxLoPsdAnchor', ...
    'RX-LO Welch anchor differs from OU theory by %.2f dB.',psdErrorDb);

% V4: adding an explicit off model leaves the historical full link exact.
p=type1_load_package(); sim=type1_offline_sim_config(); sim.frames=1;
legacy=rmfield(sim,'rxLo'); explicit=sim; explicit.rxLo.mode="off";
lLegacy=type1_offline_link(p,legacy,RandStream('mt19937ar','Seed',20261201));
lOff=type1_offline_link(p,explicit,RandStream('mt19937ar','Seed',20261201));
offCompatible=isequal(lLegacy.virtualRx30,lOff.virtualRx30) && ...
    isequal(lLegacy.stitched122,lOff.stitched122) && isequal(lLegacy.raw122,lOff.raw122);
assert(offCompatible,'type1:RxLoOffCompatibility', ...
    'Explicit RX-LO off changed the historical link samples.');
base=type1_analyze(lOff.virtualRx30,p); cpe=type1_apply_symbol_cpe(base,p);
assert(all(base.infoBitErrors==0,'all') && all(cpe.infoBitErrors==0,'all'), ...
    'type1:RxLoCpeIdeal','LO-off/CPE ideal compatibility BER is nonzero.');

report=struct('sigmaZeroExact',isequal(yzero,x),'offExact',isequal(yoff,x), ...
    'commonAcrossColumnsExact',max(abs(ycommon-ycommon(:,1)),[],'all')<1e-14, ...
    'theoreticalAlpha',exp(-2*pi*model.bandwidthHz/cfg.txSampleRate), ...
    'measuredLag1',commonMeta.phaseLag1,'welchFrequencyHz',f(bin), ...
    'welchMeasuredL',measuredL,'welchExpectedL',expectedL, ...
    'welchMeasuredDbcHz',10*log10(measuredL),'welchExpectedDbcHz',10*log10(expectedL), ...
    'welchErrorDb',psdErrorDb,'offFullLinkCompatible',offCompatible, ...
    'offBaseBitErrors',sum(base.infoBitErrors,'all'), ...
    'offCpeBitErrors',sum(cpe.infoBitErrors,'all'));
fprintf(['RX-LO validation PASSED: alpha/lag=%.8f/%.8f, L(%.1f kHz)=' ...
    '%.2f/%.2f dBc/Hz (error %.2f dB), off BER=%d/%d.\n'], ...
    report.theoreticalAlpha,report.measuredLag1,report.welchFrequencyHz/1e3, ...
    report.welchMeasuredDbcHz,report.welchExpectedDbcHz,report.welchErrorDb, ...
    report.offBaseBitErrors,report.offCpeBitErrors);
end
