function results = type1_run_phase2_tau_correlation()
%TYPE1_RUN_PHASE2_TAU_CORRELATION Reproducible OU-correlation/genie scan.
%   The frequency-correlation diagnostic is truth-aided and the beta inverse
%   is genie-aided; neither is a deployable receiver.  They decide whether a
%   banded ICI estimator is physically/statistically justified.

values=[0 8e-9 100e-9 1e-6];
summary=repmat(struct('correlationSec',nan,'standardBER',nan(1,4), ...
    'genieBER',nan(1,4),'betaLag1',nan,'frequencyLag',nan(1,2), ...
    'residualPower',nan,'tauFloorHitFraction',nan,'seed',nan),1,numel(values));
for k=1:numel(values)
    report=type1_run_phase2_genie_bound(values(k));
    summary(k)=struct('correlationSec',values(k), ...
        'standardBER',mean(report.standard.infoBER,1), ...
        'genieBER',mean(report.genie.infoBER,1), ...
        'betaLag1',report.switchMeta.fastFractionLag1Correlation, ...
        'frequencyLag',report.frequencyCorrelation.magnitudeCorrelation, ...
        'residualPower',report.frequencyCorrelation.residualPower, ...
        'tauFloorHitFraction',report.switchMeta.tauFloorHitFraction, ...
        'seed',report.seed);
end
results=struct('model','20 ns rise, fastFractionStd=0.6, SNR=20 dB', ...
    'truthAidedFrequencyDiagnostic',true,'genieBetaInverse',true,'summary',summary);
root=getenv('TYPE1_OFFLINE_OUTPUT_ROOT');if isempty(root),root=tempdir;end
out=fullfile(root,['type1_phase2_tau_correlation_' char(datetime('now','Format','yyyyMMdd_HHmmss'))]);
mkdir(out); save(fullfile(out,'phase2_tau_correlation.mat'),'results','-v7.3');
fprintf('Phase-2 tau-correlation/genie scan saved: %s\n',out);
end
